service: sls-go 

provider:
  name: aws
  runtime: go1.x
  versionFunctions: true
  logRetentionInDays: 30

package:
  individually: true
  exclude:
    - ./**

functions:
  hello:
    handler: bin/hello
    package:
      include:
        - ./bin/hello
  world:
    handler: bin/world
    package:
      include:
        - ./bin/world