service: sls-go # NOTE: update this with your service name=

provider:
  name: aws
  runtime: go1.x
  versionFunctions: true

package:
  individually: true
  exclude:
    - ./**

functions:
  hello:
    handler: bin/hello
    package:
      include:
        - ./bin/hello
  world:
    handler: bin/world
    package:
      include:
        - ./bin/world